export type GlossaryCategory = 'Core Concepts' | 'Scheduling' | 'Cost & Value' | 'Risk' | 'Quality' | 'Agile' | 'Stakeholder & Communication' | 'Procurement' | 'Integration'

export interface GlossaryTerm {
  term: string
  definition: string
  category: GlossaryCategory
  acronym?: string
}

export const glossaryTerms: GlossaryTerm[] = [
  // Core Concepts
  { term: 'Project', category: 'Core Concepts', definition: 'A temporary endeavor undertaken to create a unique product, service, or result. Projects have a defined beginning and end, and are different from ongoing operations.' },
  { term: 'Project Management', category: 'Core Concepts', definition: 'The application of knowledge, skills, tools, and techniques to project activities to meet project requirements. Accomplished through processes such as initiating, planning, executing, monitoring and controlling, and closing.' },
  { term: 'Program', category: 'Core Concepts', definition: 'A group of related projects, subsidiary programs, and program activities managed in a coordinated manner to obtain benefits not available from managing them individually.' },
  { term: 'Portfolio', category: 'Core Concepts', definition: 'Projects, programs, subsidiary portfolios, and operations managed as a group to achieve strategic objectives. Portfolio components are not necessarily interdependent or directly related.' },
  { term: 'Project Charter', category: 'Core Concepts', acronym: 'PC', definition: 'A document issued by the project initiator or sponsor that formally authorizes the existence of a project and provides the project manager with the authority to apply organizational resources to project activities.' },
  { term: 'Project Management Plan', category: 'Core Concepts', acronym: 'PMP', definition: 'The document that describes how the project will be executed, monitored, controlled, and closed. Integrates all subsidiary plans and baselines.' },
  { term: 'Work Breakdown Structure', category: 'Core Concepts', acronym: 'WBS', definition: 'A hierarchical decomposition of the total scope of work to be carried out by the project team to accomplish the project objectives and create the required deliverables. The lowest level of the WBS is the work package.' },
  { term: 'Deliverable', category: 'Core Concepts', definition: 'Any unique and verifiable product, result, or capability to perform a service that is required to be produced to complete a process, phase, or project.' },
  { term: 'Milestone', category: 'Core Concepts', definition: 'A significant point or event in a project. Milestones have zero duration and represent the completion of a major deliverable or phase. They are used to track project progress.' },
  { term: 'Scope Creep', category: 'Core Concepts', definition: 'The uncontrolled expansion of product or project scope without adjustments to time, cost, and resources. Occurs when changes are made without going through the formal change control process.' },
  { term: 'Triple Constraint', category: 'Core Concepts', definition: 'The framework for evaluating competing project demands: scope, time (schedule), and cost. Changes to one constraint typically affect the others. Quality is sometimes added as a fourth constraint.' },
  { term: 'Organizational Process Assets', category: 'Core Concepts', acronym: 'OPAs', definition: 'Plans, processes, policies, procedures, and knowledge bases specific to and used by the performing organization. Include lessons learned, historical data, templates, and organizational standards.' },
  { term: 'Enterprise Environmental Factors', category: 'Core Concepts', acronym: 'EEFs', definition: 'Conditions not under the immediate control of the team that influence, constrain, or direct the project. Include organizational culture, government regulations, market conditions, and infrastructure.' },
  { term: 'Lessons Learned', category: 'Core Concepts', definition: 'The knowledge gained during a project about what worked well, what did not work, and what should be done differently. Captured throughout the project and stored in a lessons learned repository for future reference.' },
  { term: 'Stakeholder', category: 'Stakeholder & Communication', definition: 'An individual, group, or organization that may affect, be affected by, or perceive itself to be affected by a decision, activity, or outcome of a project. Stakeholders can have a positive or negative influence.' },

  // Scheduling
  { term: 'Critical Path', category: 'Scheduling', definition: 'The sequence of activities that represents the longest path through a project, which determines the shortest possible project duration. Activities on the critical path have zero float.' },
  { term: 'Critical Path Method', category: 'Scheduling', acronym: 'CPM', definition: 'A schedule network analysis technique used to determine the amount of scheduling flexibility (float) on various logical network paths in the project schedule network and to determine the minimum total project duration.' },
  { term: 'Float', category: 'Scheduling', definition: 'Also called slack. The amount of time an activity can be delayed without delaying a subsequent activity (free float) or the project end date (total float). Activities on the critical path have zero total float.' },
  { term: 'Fast Tracking', category: 'Scheduling', definition: 'A schedule compression technique in which activities or phases normally done in sequence are performed in parallel for at least a portion of their duration. Increases risk of rework.' },
  { term: 'Crashing', category: 'Scheduling', definition: 'A schedule compression technique in which additional resources are added to shorten the schedule for the least incremental cost. Increases project cost. Only effective on critical path activities.' },
  { term: 'Lag', category: 'Scheduling', definition: 'The amount of time whereby a successor activity is required to be delayed with respect to a predecessor activity. For example, concrete must cure for 3 days before painting can begin (Finish-to-Start + 3 days lag).' },
  { term: 'Lead', category: 'Scheduling', definition: 'The amount of time whereby a successor activity can be advanced with respect to a predecessor activity. A negative lag. For example, start writing user documentation 2 weeks before development finishes.' },
  { term: 'PERT', category: 'Scheduling', acronym: 'PERT', definition: 'Program Evaluation and Review Technique. Uses weighted average of three-point estimates: (Optimistic + 4 x Most Likely + Pessimistic) / 6. Used to determine expected activity duration and estimate schedule uncertainty.' },
  { term: 'Gantt Chart', category: 'Scheduling', definition: 'A bar chart that shows the project schedule. Activities are listed on the vertical axis, and the horizontal axis represents time. Bars show start and end dates of activities. Dependencies can be shown with arrows.' },
  { term: 'Precedence Diagramming Method', category: 'Scheduling', acronym: 'PDM', definition: 'A technique used to construct a schedule model in which activities are represented by nodes and are graphically linked by one or more logical relationships to show the sequence in which activities are to be performed.' },
  { term: 'Resource Leveling', category: 'Scheduling', definition: 'A technique in which start and finish dates are adjusted based on resource constraints to balance demand for resources with available supply. Often results in a longer project duration.' },
  { term: 'Schedule Baseline', category: 'Scheduling', definition: 'The approved version of a schedule model that can be changed only through formal change control procedures and is used as a basis for comparison to actual results.' },
  { term: 'Monte Carlo Simulation', category: 'Scheduling', definition: 'A technique that computes or iterates the project cost or project schedule many times using input values selected at random from probability distributions to simulate the range of possible outcomes.' },

  // Cost & Value
  { term: 'Earned Value', category: 'Cost & Value', acronym: 'EV', definition: 'The measure of work performed expressed in terms of the budget authorized for that work. EV = % Complete x BAC. Represents the budgeted cost of work actually completed.' },
  { term: 'Planned Value', category: 'Cost & Value', acronym: 'PV', definition: 'The authorized budget assigned to scheduled work. The "planned" amount of budget that should have been spent by a given point in time.' },
  { term: 'Actual Cost', category: 'Cost & Value', acronym: 'AC', definition: 'The realized cost incurred for the work performed on an activity during a specific time period. What was actually spent.' },
  { term: 'Budget at Completion', category: 'Cost & Value', acronym: 'BAC', definition: 'The sum of all budgets established for the work to be performed. The total planned budget for the project.' },
  { term: 'Cost Performance Index', category: 'Cost & Value', acronym: 'CPI', definition: 'A measure of the cost efficiency of budgeted resources expressed as a ratio of earned value to actual cost. CPI = EV / AC. CPI > 1.0 is favorable (under budget), CPI < 1.0 is unfavorable (over budget).' },
  { term: 'Schedule Performance Index', category: 'Cost & Value', acronym: 'SPI', definition: 'A measure of schedule efficiency expressed as a ratio of earned value to planned value. SPI = EV / PV. SPI > 1.0 means ahead of schedule; SPI < 1.0 means behind schedule.' },
  { term: 'Cost Variance', category: 'Cost & Value', acronym: 'CV', definition: 'The amount of budget deficit or surplus at a given point in time. CV = EV - AC. Positive CV means under budget; negative CV means over budget.' },
  { term: 'Schedule Variance', category: 'Cost & Value', acronym: 'SV', definition: 'A measure of schedule performance expressed as the difference between earned value and planned value. SV = EV - PV. Positive SV means ahead of schedule; negative SV means behind schedule.' },
  { term: 'Estimate at Completion', category: 'Cost & Value', acronym: 'EAC', definition: 'The expected total cost of completing all work expressed as the sum of actual cost to date plus an estimate to complete remaining work. Common formula: EAC = AC + (BAC - EV) or EAC = BAC / CPI.' },
  { term: 'Estimate to Complete', category: 'Cost & Value', acronym: 'ETC', definition: 'The expected cost needed to finish all the remaining work on the project. ETC = EAC - AC.' },
  { term: 'Variance at Completion', category: 'Cost & Value', acronym: 'VAC', definition: 'A projection of the amount of budget deficit or surplus, expressed as the difference between budget at completion and estimate at completion. VAC = BAC - EAC.' },
  { term: 'Reserve Analysis', category: 'Cost & Value', definition: 'A technique used to assess the amount of risk or uncertainty remaining in the project and determine what contingency and management reserves should be set aside in the project budget.' },
  { term: 'Contingency Reserve', category: 'Cost & Value', definition: 'Budget within the cost baseline that is allocated for identified risks for which contingent or mitigating responses are developed. Used to handle known-unknowns. Managed by the project manager.' },
  { term: 'Management Reserve', category: 'Cost & Value', definition: 'An amount of the project budget or project schedule held outside of the performance measurement baseline for management control purposes. Used for unknown-unknowns. Requires sponsor approval to access.' },

  // Risk
  { term: 'Risk', category: 'Risk', definition: 'An uncertain event or condition that, if it occurs, has a positive or negative effect on one or more project objectives such as scope, schedule, cost, or quality. Risks can be threats (negative) or opportunities (positive).' },
  { term: 'Risk Register', category: 'Risk', definition: 'A repository in which outputs of risk management processes are recorded. Contains identified risks, potential risk owners, potential risk responses, root causes, risk categories, current status, and probability/impact assessments.' },
  { term: 'Probability and Impact Matrix', category: 'Risk', definition: 'A grid for mapping the probability of each risk occurrence and its impact on project objectives if that risk occurs. Risks are rated based on their probability and impact to prioritize them for further analysis or action.' },
  { term: 'Expected Monetary Value', category: 'Risk', acronym: 'EMV', definition: 'A statistical concept that calculates the average outcome when the future includes scenarios that may or may not happen. EMV = Probability x Impact ($). Used in decision tree analysis.' },
  { term: 'Risk Avoidance', category: 'Risk', definition: 'A risk response strategy whereby the project team acts to eliminate the threat or protect the project from its impact. Usually involves changing the project management plan.' },
  { term: 'Risk Mitigation', category: 'Risk', definition: 'A risk response strategy whereby the project team acts to decrease the probability of occurrence or impact of a threat. Actions are taken before a risk occurs to reduce its likelihood or consequences.' },
  { term: 'Risk Transfer', category: 'Risk', definition: 'A risk response strategy whereby the project team shifts the impact of a threat to a third party, together with ownership of the response. Does not eliminate the risk. Examples: insurance, warranties, fixed-price contracts.' },
  { term: 'Risk Acceptance', category: 'Risk', definition: 'A risk response strategy whereby the project team decides to acknowledge the risk and not take any action unless the risk occurs. Can be active (contingency plan) or passive (acknowledge and monitor).' },
  { term: 'Residual Risk', category: 'Risk', definition: 'The risk that remains after risk responses have been implemented.' },
  { term: 'Secondary Risk', category: 'Risk', definition: 'A risk that arises as a direct result of implementing a risk response. For example, the response to one risk introduces a new risk.' },
  { term: 'Workaround', category: 'Risk', definition: 'An unplanned response to a risk that was not identified in advance or accepted. Workarounds address the impact of risks that have already occurred.' },
  { term: 'Qualitative Risk Analysis', category: 'Risk', definition: 'The process of prioritizing individual project risks for further analysis or action by assessing their probability of occurrence and impact using probability and impact matrix. A subjective assessment approach.' },
  { term: 'Quantitative Risk Analysis', category: 'Risk', definition: 'The process of numerically analyzing the combined effect of identified individual project risks and other sources of uncertainty on overall project objectives. Uses EMV, Monte Carlo, decision trees.' },

  // Quality
  { term: 'Quality', category: 'Quality', definition: 'The degree to which a set of inherent characteristics fulfills requirements. In project management, quality means the product meets stated and implied stakeholder needs and the project processes are carried out correctly.' },
  { term: 'Quality Assurance', category: 'Quality', acronym: 'QA', definition: 'The process of auditing the quality requirements and the results from quality control measurements to ensure that appropriate quality standards and operational definitions are used. Focuses on process improvement.' },
  { term: 'Quality Control', category: 'Quality', acronym: 'QC', definition: 'The process of monitoring and recording results of executing quality activities to assess performance and recommend necessary changes. Focuses on product inspection and defect identification.' },
  { term: 'Control Chart', category: 'Quality', definition: 'A graphic display of process data over time and against established control limits. Used to determine whether a process is stable and predictable. Points outside control limits or patterns indicate special cause variation.' },
  { term: 'Cause and Effect Diagram', category: 'Quality', definition: 'Also called Ishikawa or fishbone diagram. A decomposition technique that helps trace an undesirable effect back to its root cause. Categories often include: Methods, Machines, Materials, Measurement, Environment, People.' },
  { term: 'Pareto Chart', category: 'Quality', definition: 'A histogram, ordered by frequency of occurrence, that shows how many results were generated by each identified cause. Based on the Pareto principle (80/20 rule): 80% of problems come from 20% of causes.' },
  { term: 'Cost of Quality', category: 'Quality', acronym: 'COQ', definition: 'All costs incurred over the life of the product by investment in preventing nonconformance, appraisal of conformance, and failure to meet requirements. Includes prevention costs, appraisal costs, and failure costs (internal and external).' },
  { term: 'Grade', category: 'Quality', definition: 'A category assigned to deliverables having the same functional use but different technical characteristics. Low quality is always a problem; low grade may not be. A product can be high quality but low grade (e.g., basic text editor vs. MS Word).' },
  { term: 'Rule of Seven', category: 'Quality', definition: 'A rule in statistical process control stating that if seven consecutive data points fall on the same side of the mean on a control chart, the process is considered out of control, even if the points are within control limits.' },

  // Agile
  { term: 'Sprint', category: 'Agile', definition: 'A time-boxed iteration of one to four weeks during which the Scrum team creates a potentially shippable product increment. The length of a sprint is fixed and consistent throughout the project.' },
  { term: 'Product Backlog', category: 'Agile', definition: 'An ordered list of everything that is known to be needed in the product. The single source of requirements for any changes to be made to the product. Maintained and prioritized by the Product Owner.' },
  { term: 'Sprint Backlog', category: 'Agile', definition: 'The set of Product Backlog items selected for the sprint, plus a plan for delivering the product increment and realizing the sprint goal. Owned by the development team.' },
  { term: 'Velocity', category: 'Agile', definition: 'The amount of work a team can complete in a single sprint, measured in story points or other units. Used to forecast future delivery capacity. Velocity is determined empirically over multiple sprints.' },
  { term: 'User Story', category: 'Agile', definition: 'A brief, informal description of a feature told from the perspective of the person who desires the functionality. Format: As a [type of user], I want [some goal] so that [some reason]. Used to capture requirements in Agile projects.' },
  { term: 'Definition of Done', category: 'Agile', acronym: 'DoD', definition: 'A shared understanding of what it means for work to be complete. A checklist of quality criteria that must be met before a user story or sprint increment is considered done. Ensures consistent quality standards.' },
  { term: 'Retrospective', category: 'Agile', definition: 'A regular meeting held at the end of each sprint or iteration where the team reflects on what went well, what did not go well, and what improvements to make. Central to continuous improvement in Agile.' },
  { term: 'Kanban', category: 'Agile', definition: 'A method for visualizing workflow, limiting work in progress (WIP), and managing flow. Uses a Kanban board with columns representing stages of work. Originated in lean manufacturing at Toyota.' },
  { term: 'Scrum', category: 'Agile', definition: 'An Agile framework for developing and delivering complex products. Uses fixed-length sprints, specific roles (Product Owner, Scrum Master, Development Team), and ceremonies (Sprint Planning, Daily Scrum, Sprint Review, Retrospective).' },
  { term: 'Product Owner', category: 'Agile', definition: 'The Scrum role responsible for maximizing the value of the product by managing and prioritizing the Product Backlog. Represents the voice of the customer and stakeholders.' },
  { term: 'Scrum Master', category: 'Agile', definition: 'The Scrum role responsible for promoting and supporting Scrum by helping everyone understand Scrum theory, practices, rules, and values. Removes impediments to team progress and facilitates Scrum events.' },
  { term: 'Burndown Chart', category: 'Agile', definition: 'A graphical representation of work left to do versus time. The outstanding work (or backlog) is often on the vertical axis, with time along the horizontal. Shows whether the team is on track to complete the sprint or release.' },
  { term: 'MVP', category: 'Agile', acronym: 'MVP', definition: 'Minimum Viable Product. The smallest version of a product that delivers enough value to satisfy early customers and provides feedback for future development. Reduces waste by testing assumptions before full investment.' },
  { term: 'Story Points', category: 'Agile', definition: 'A unit of measure for expressing an estimate of the overall effort required to fully implement a product backlog item or any other piece of work. Abstract units that represent relative size, complexity, and uncertainty.' },
  { term: 'Daily Scrum', category: 'Agile', definition: 'A 15-minute time-boxed daily event for the development team to synchronize activities and create a plan for the next 24 hours. Each member answers: What did I do yesterday? What will I do today? Are there any impediments?' },

  // Stakeholder & Communication
  { term: 'Communications Management Plan', category: 'Stakeholder & Communication', definition: 'A component of the project management plan that describes how project communications will be planned, structured, implemented, and monitored for effectiveness. Includes who needs what information, when, in what format, and through what channel.' },
  { term: 'Stakeholder Engagement Plan', category: 'Stakeholder & Communication', definition: 'A component of the project management plan that identifies the strategies and actions required to promote productive involvement of stakeholders in project decision making and execution.' },
  { term: 'Power/Interest Grid', category: 'Stakeholder & Communication', definition: 'A stakeholder analysis tool that categorizes stakeholders based on their level of authority (power) and their level of concern regarding project outcomes (interest). Used to prioritize stakeholder engagement strategies.' },
  { term: 'RACI Matrix', category: 'Stakeholder & Communication', definition: 'A type of responsibility assignment matrix that uses Responsible, Accountable, Consulted, and Informed to clarify roles and responsibilities. Ensures everyone knows who does what.' },
  { term: 'Issue Log', category: 'Stakeholder & Communication', definition: 'A project document where information about issues is recorded and monitored. Issues are problems that require resolution and may impact the project. Different from risks, which are uncertain future events.' },
  { term: 'Push Communication', category: 'Stakeholder & Communication', definition: 'Information sent directly to specific recipients who need to know it. Examples: emails, memos, letters, reports. The sender determines who receives the information.' },
  { term: 'Pull Communication', category: 'Stakeholder & Communication', definition: 'Information placed in a central repository for recipients to access at their discretion. Examples: intranet portals, knowledge repositories, web portals. Used for very large audiences or large volumes of information.' },

  // Procurement
  { term: 'Statement of Work', category: 'Procurement', acronym: 'SOW', definition: 'A narrative description of products, services, or results to be delivered by the project. Includes specifications, quantities, quality requirements, and performance criteria for procured work.' },
  { term: 'Request for Proposal', category: 'Procurement', acronym: 'RFP', definition: 'A type of procurement document used to request proposals from prospective sellers of products or services. Used when the buyer needs to evaluate vendor approaches, qualifications, and price — not just price alone.' },
  { term: 'Request for Quote', category: 'Procurement', acronym: 'RFQ', definition: 'A type of procurement document used to request price quotations from prospective sellers. Used when the requirements are clear and the selection will be based primarily on price.' },
  { term: 'Fixed Price Contract', category: 'Procurement', definition: 'A contract type that sets the fee to be paid for a defined scope of work regardless of the seller's actual costs. Transfers cost risk to the seller. Types: FFP (Firm Fixed Price), FPIF (Fixed Price Incentive Fee), FP-EPA (Fixed Price with Economic Price Adjustment).' },
  { term: 'Cost Reimbursable Contract', category: 'Procurement', definition: 'A contract type where the buyer reimburses the seller for all allowable costs incurred for performing the contract work, plus a fee representing seller profit. Transfers cost risk to the buyer. Types: CPFF, CPIF, CPAF.' },
  { term: 'Time and Material Contract', category: 'Procurement', acronym: 'T&M', definition: 'A type of contract that is a hybrid of cost-reimbursable and fixed-price arrangements. Unit rates are fixed, but total cost is variable based on time spent and materials used. Suitable for when scope cannot be precisely defined.' },

  // Integration
  { term: 'Integrated Change Control', category: 'Integration', definition: 'The process of reviewing all change requests; approving changes and managing changes to deliverables, project documents, and the project management plan; and communicating decisions. Ensures changes are considered holistically.' },
  { term: 'Change Control Board', category: 'Integration', acronym: 'CCB', definition: 'A formally chartered group responsible for reviewing, evaluating, approving, delaying, or rejecting changes to the project, and for recording and communicating change decisions.' },
  { term: 'Configuration Management System', category: 'Integration', definition: 'A collection of formal documented procedures used to apply technical and administrative direction and surveillance to identify and document the functional and physical characteristics of a product, result, or component.' },
  { term: 'Benefits Realization Plan', category: 'Integration', definition: 'A document that describes how and when the project will deliver the benefits defined in the business case, and the mechanism by which they will be measured. Extends beyond the project into operations.' },
  { term: 'Business Case', category: 'Integration', definition: 'A documented economic feasibility study used to establish the validity of the benefits of a selected component lacking sufficient definition and that is used as a basis for the authorization of further project management activities.' },
]
